### ISSUE TITLE
运行时出错

### ISSUE THREAD

**Issue by dknightlx** [easton402/Taobao_Crawler#1]
### 您好，非常抱歉打扰您的工作，但是我在运行该程序时出现错误。惭愧的是我无法处理这个错误。

`python start_scrape_taobao.py`
运行后出现错误，错误代码：
`2016-02-20 12:01:06 [scrapy] INFO: Scrapy 1.1.0rc1 started (bot: scrapybot)
2016-02-20 12:01:06 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'taobao_crawler.spiders', 'SPIDER_MODULES': ['taobao_crawler.spiders'], 'RETRY_TIMES': 3, 'COOKIES_ENABLED': False, 'CONCURRENT_REQUESTS_PER_IP': 2, 'DEFAULT_ITEM_CLASS': 'taobao_crawler.items.Website', 'DOWNLOAD_DELAY': 2}
2016-02-20 12:01:06 [scrapy] INFO: Enabled extensions:
['scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.spiderstate.SpiderState']
2016-02-20 12:01:06 [py.warnings] WARNING: C:\Python27\lib\site-packages\scrapy-1.1.0rc1-py2.7.egg\scrapy\utils\deprecate.py:156: ScrapyDeprecationWarning:`scrapy.contrib.downloadermiddleware.useragent.UserAgentMiddleware`class is deprecated, use`scrapy.downloadermiddlewares.useragent.UserAgentMiddleware` instead
  ScrapyDeprecationWarning)

**Unhandled error in Deferred:
2016-02-20 12:01:06 [twisted] CRITICAL: Unhandled error in Deferred:**

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\scrapy-1.1.0rc1-py2.7.egg\scrapy\crawler.py", line 152, in crawl
    return self._crawl(crawler, _args, *_kwargs)
  File "C:\Python27\lib\site-packages\scrapy-1.1.0rc1-py2.7.egg\scrapy\crawler.py", line 156, in _crawl
    d = crawler.crawl(_args, *_kwargs)
  File "C:\Python27\lib\site-packages\twisted-15.5.0-py2.7-win-amd64.egg\twisted\internet\defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
  File "C:\Python27\lib\site-packages\twisted-15.5.0-py2.7-win-amd64.egg\twisted\internet\defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
--- <exception caught here> ---
  File "C:\Python27\lib\site-packages\scrapy-1.1.0rc1-py2.7.egg\scrapy\crawler.py", line 71, in crawl
    self.engine = self._create_engine()
  File "C:\Python27\lib\site-packages\scrapy-1.1.0rc1-py2.7.egg\scrapy\crawler.py", line 86, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "C:\Python27\lib\site-packages\scrapy-1.1.0rc1-py2.7.egg\scrapy\core\engine.py", line 68, in __init__
    self.downloader = downloader_cls(crawler)
  File "C:\Python27\lib\site-packages\scrapy-1.1.0rc1-py2.7.egg\scrapy\core\downloader__init__.py", line 88, in **init**
    self.middleware = DownloaderMiddlewareManager.from_crawler(crawler)
  File "C:\Python27\lib\site-packages\scrapy-1.1.0rc1-py2.7.egg\scrapy\middleware.py", line 58, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "C:\Python27\lib\site-packages\scrapy-1.1.0rc1-py2.7.egg\scrapy\middleware.py", line 34, in from_settings
    mwcls = load_object(clspath)
  File "C:\Python27\lib\site-packages\scrapy-1.1.0rc1-py2.7.egg\scrapy\utils\misc.py", line 44, in load_object
    mod = import_module(module)
  File "C:\Python27\lib\importlib__init__.py", line 37, in import_module
    **import**(name)
**exceptions.ImportError: No module named random_useragent**
2016-02-20 12:01:06 [twisted] CRITICAL:`

**Comment by EastonLee** [comment]
根据日志，你的开发环境缺失一些包，执行下面命令安装缺失的两个包：
`pip install MySQL-python scrapy-random-useragent`
